package aws

import "github.com/rusik69/lc/internal/problems"

func init() {
	problems.RegisterAWSModules([]problems.CourseModule{
		{
			ID:          2118,
			Title:       "AWS Security and Identity Management",
			Description: "Deep dive into IAM policies, Organizations, SCPs, AWS SSO, KMS encryption, Secrets Manager, GuardDuty, and security best practices.",
			Order:       18,
			Lessons: []problems.Lesson{
				{
					Title: "IAM Security KMS and AWS Security Services",
					Content: `AWS security is built on Identity and Access Management with defense-in-depth through encryption, monitoring, and compliance services.

**IAM Deep Dive:**

IAM Principals:
  Root Account: Full access, never use for daily tasks
  IAM Users: Long-term credentials
  IAM Roles: Temporary credentials (assume role)
  Federated Users: External identity (SAML, OIDC)
  Service Principals: AWS services

IAM Policies:
  Identity-based: Attached to user/group/role
  Resource-based: Attached to resource (S3 bucket, SQS queue)
  Permission Boundaries: Max permissions for a principal
  Organizations SCPs: Max permissions for an account
  Session Policies: Limit role session permissions
  
  Policy Evaluation Logic:
    1. Start with implicit DENY
    2. Evaluate all applicable policies
    3. Any explicit DENY -> DENY (final)
    4. Any explicit ALLOW -> check boundaries
    5. Permission boundary ALLOW? -> check SCP
    6. SCP ALLOW? -> ALLOW
    7. Otherwise -> implicit DENY

  Policy Structure:
    Version: "2012-10-17"
    Statement:
      Effect: Allow/Deny
      Action: service:action (s3:GetObject)
      Resource: ARN of resource
      Condition: Context-based restrictions
      Principal: Who (resource-based only)
      
  Condition Keys:
    aws:SourceIp: Request IP address
    aws:RequestedRegion: Target region
    aws:PrincipalTag: Tag on principal
    aws:ResourceTag: Tag on resource
    aws:CurrentTime: Current time
    aws:MultiFactorAuthPresent: MFA used
    aws:SecureTransport: HTTPS used
    s3:prefix: S3 key prefix
    ec2:ResourceTag: EC2 resource tag

  Policy Best Practices:
    Least privilege: Only needed permissions
    Use conditions: Restrict by IP, time, MFA
    Use resource ARNs: Not wildcards
    Regular review: Access Analyzer findings
    Use managed policies: AWS-maintained
    Permission boundaries for delegated admin

**AWS Organizations:**

  Multi-account management
  
  Structure:
    Management Account (root)
    Organizational Units (OUs)
    Member Accounts
    
  OU Design:
    Root
    ├── Security OU
    │   ├── Log Archive Account
    │   └── Security Tooling Account
    ├── Infrastructure OU
    │   ├── Networking Account
    │   └── Shared Services Account
    ├── Workloads OU
    │   ├── Production OU
    │   │   ├── App A Prod Account
    │   │   └── App B Prod Account
    │   └── Non-Production OU
    │       ├── App A Dev Account
    │       └── App A Staging Account
    └── Sandbox OU
        └── Developer Sandbox Accounts

  Service Control Policies (SCPs):
    Restrict permissions for entire OU/account
    Does NOT grant permissions
    Applied in hierarchy (inherited)
    Management account exempt
    
    Common SCPs:
      Deny region restriction (only us-east-1, eu-west-1)
      Deny leaving organization
      Deny disabling CloudTrail
      Deny disabling GuardDuty
      Require encryption on S3
      Deny root user access

**AWS IAM Identity Center (SSO):**

  Centralized workforce access
  Single sign-on to AWS accounts and applications
  
  Identity Sources:
    IAM Identity Center directory
    Active Directory (AD Connector, AWS Managed AD)
    External IdP (Okta, Azure AD via SAML/SCIM)
    
  Permission Sets:
    Define permissions granted in target account
    Mapped to users/groups for each account
    Creates IAM roles automatically
    
  Features:
    Multi-account access portal
    Application assignments
    ABAC (attribute-based access control)
    Session duration configuration
    CLI/API access (aws sso login)

**AWS KMS (Key Management Service):**

  Managed encryption keys
  
  Key Types:
    AWS Managed Keys: aws/s3, aws/ebs, etc.
    Customer Managed Keys (CMK): You create and manage
    Customer Provided Keys: Import your own
    
  Key Material Origin:
    KMS: Generated by AWS
    External: Imported by you
    CloudHSM: Generated in CloudHSM cluster
    
  Key Policies:
    Default: Account root has full access
    Key administrators: Manage key (not use it)
    Key users: Use key for encrypt/decrypt
    Grants: Temporary, specific permissions
    
  Encryption Types:
    Symmetric (AES-256): Default, most services
    Asymmetric (RSA, ECC): Sign/verify, encrypt outside AWS
    HMAC: Message authentication codes
    
  Key Operations:
    Encrypt: Plaintext -> Ciphertext (max 4KB)
    Decrypt: Ciphertext -> Plaintext
    GenerateDataKey: Returns plaintext + encrypted data key
    GenerateDataKeyWithoutPlaintext: Returns only encrypted key
    
  Envelope Encryption:
    Data Key encrypts data (local)
    KMS key encrypts data key
    Store encrypted data + encrypted data key
    Decrypt: KMS decrypts data key, then decrypt data locally
    
  Key Rotation:
    Automatic: Annual rotation (recommended)
    Manual: Create new key, update aliases
    Imported keys: Manual only
    
  Multi-Region Keys:
    Primary key + replica keys in other regions
    Same key material, same key ID
    Disaster recovery, global applications

**AWS Secrets Manager:**

  Rotate, manage, retrieve secrets
  Automatic rotation with Lambda
  Integration with RDS, Redshift, DocumentDB
  Cross-account access via resource policy
  Versioning (AWSCURRENT, AWSPREVIOUS)
  
  Rotation:
    Lambda function rotates secret
    Built-in rotation for RDS, Redshift
    Custom rotation for other secrets
    Schedule: Days between rotations

**AWS Security Services:**

GuardDuty:
  Threat detection service
  Analyzes: CloudTrail, VPC Flow Logs, DNS Logs
  Findings: Reconnaissance, instance compromise, account compromise
  Machine learning and threat intelligence
  Multi-account via Organizations

Security Hub:
  Central security findings dashboard
  Aggregates from GuardDuty, Inspector, Macie, etc.
  Security standards: CIS, PCI DSS, AWS Foundational
  Automated remediation with EventBridge

AWS Inspector:
  Vulnerability scanning
  EC2 instances and ECR images
  CVE-based findings
  Network reachability analysis
  Software composition analysis

AWS Macie:
  S3 data classification
  PII/sensitive data discovery
  Uses machine learning
  Automated monitoring and alerting

CloudTrail:
  API activity logging
  Management events (default: 90 days free)
  Data events (S3 object, Lambda invocation)
  Organization trail: All accounts
  CloudTrail Lake: SQL-based query
  Integrity validation: Detect log tampering

AWS Config:
  Resource configuration recording
  Configuration compliance rules
  Remediation actions (SSM Automation)
  Aggregator for multi-account
  Conformance packs (compliance templates)`,
					CodeExamples: `// AWS security and IAM implementations

package main

import (
    "encoding/json"
    "fmt"
    "net"
    "strings"
    "sync"
    "time"
)

// IAM policy evaluator
type IAMPolicyEvaluator struct {
    identityPolicies   map[string][]IAMPolicy
    resourcePolicies   map[string]IAMPolicy
    permissionBounds   map[string]IAMPolicy
    scps               []IAMPolicy
    mu                 sync.RWMutex
}

type IAMPolicy struct {
    Version    string
    Statements []IAMStatement
}

type IAMStatement struct {
    Sid       string
    Effect    string // Allow, Deny
    Action    []string
    Resource  []string
    Condition map[string]map[string]string
    Principal []string // For resource-based policies
}

type IAMRequest struct {
    Principal   string
    Action      string
    Resource    string
    SourceIP    string
    MFAPresent  bool
    Tags        map[string]string
    Time        time.Time
}

type IAMDecision struct {
    Allowed bool
    Reason  string
    Matched string
}

func NewIAMPolicyEvaluator() *IAMPolicyEvaluator {
    return &IAMPolicyEvaluator{
        identityPolicies: make(map[string][]IAMPolicy),
        resourcePolicies: make(map[string]IAMPolicy),
        permissionBounds: make(map[string]IAMPolicy),
    }
}

func (e *IAMPolicyEvaluator) AttachPolicy(principal string, policy IAMPolicy) {
    e.mu.Lock()
    defer e.mu.Unlock()
    e.identityPolicies[principal] = append(e.identityPolicies[principal], policy)
}

func (e *IAMPolicyEvaluator) SetPermissionBoundary(principal string, policy IAMPolicy) {
    e.mu.Lock()
    defer e.mu.Unlock()
    e.permissionBounds[principal] = policy
}

func (e *IAMPolicyEvaluator) AddSCP(policy IAMPolicy) {
    e.mu.Lock()
    defer e.mu.Unlock()
    e.scps = append(e.scps, policy)
}

func (e *IAMPolicyEvaluator) Evaluate(req IAMRequest) IAMDecision {
    e.mu.RLock()
    defer e.mu.RUnlock()
    
    // Step 1: Check explicit denies in all policies
    allPolicies := e.getAllPolicies(req.Principal, req.Resource)
    for _, policy := range allPolicies {
        for _, stmt := range policy.Statements {
            if stmt.Effect != "Deny" {
                continue
            }
            if matchAction(stmt.Action, req.Action) && matchResource(stmt.Resource, req.Resource) {
                if evaluateConditions(stmt.Condition, req) {
                    return IAMDecision{
                        Allowed: false,
                        Reason:  "Explicit DENY",
                        Matched: stmt.Sid,
                    }
                }
            }
        }
    }
    
    // Step 2: Check SCPs
    if len(e.scps) > 0 {
        scpAllowed := false
        for _, scp := range e.scps {
            for _, stmt := range scp.Statements {
                if stmt.Effect == "Allow" && matchAction(stmt.Action, req.Action) {
                    if matchResource(stmt.Resource, req.Resource) {
                        scpAllowed = true
                        break
                    }
                }
            }
        }
        if !scpAllowed {
            return IAMDecision{Allowed: false, Reason: "SCP deny"}
        }
    }
    
    // Step 3: Check permission boundary
    if boundary, hasBoundary := e.permissionBounds[req.Principal]; hasBoundary {
        boundaryAllowed := false
        for _, stmt := range boundary.Statements {
            if stmt.Effect == "Allow" && matchAction(stmt.Action, req.Action) {
                if matchResource(stmt.Resource, req.Resource) {
                    boundaryAllowed = true
                    break
                }
            }
        }
        if !boundaryAllowed {
            return IAMDecision{Allowed: false, Reason: "Permission boundary deny"}
        }
    }
    
    // Step 4: Check identity-based allows
    identityPolicies := e.identityPolicies[req.Principal]
    for _, policy := range identityPolicies {
        for _, stmt := range policy.Statements {
            if stmt.Effect == "Allow" && matchAction(stmt.Action, req.Action) {
                if matchResource(stmt.Resource, req.Resource) {
                    if evaluateConditions(stmt.Condition, req) {
                        return IAMDecision{
                            Allowed: true,
                            Reason:  "Identity policy allow",
                            Matched: stmt.Sid,
                        }
                    }
                }
            }
        }
    }
    
    // Step 5: Check resource-based allows
    if resPolicy, hasResPolicy := e.resourcePolicies[req.Resource]; hasResPolicy {
        for _, stmt := range resPolicy.Statements {
            if stmt.Effect == "Allow" && matchAction(stmt.Action, req.Action) {
                if matchPrincipal(stmt.Principal, req.Principal) {
                    if evaluateConditions(stmt.Condition, req) {
                        return IAMDecision{
                            Allowed: true,
                            Reason:  "Resource policy allow",
                            Matched: stmt.Sid,
                        }
                    }
                }
            }
        }
    }
    
    return IAMDecision{Allowed: false, Reason: "Implicit DENY (no matching allow)"}
}

func (e *IAMPolicyEvaluator) getAllPolicies(principal, resource string) []IAMPolicy {
    var all []IAMPolicy
    all = append(all, e.identityPolicies[principal]...)
    if resPolicy, ok := e.resourcePolicies[resource]; ok {
        all = append(all, resPolicy)
    }
    if boundary, ok := e.permissionBounds[principal]; ok {
        all = append(all, boundary)
    }
    all = append(all, e.scps...)
    return all
}

func matchAction(patterns []string, action string) bool {
    for _, p := range patterns {
        if p == "*" || strings.EqualFold(p, action) {
            return true
        }
        if strings.HasSuffix(p, "*") {
            prefix := strings.TrimSuffix(p, "*")
            if strings.HasPrefix(strings.ToLower(action), strings.ToLower(prefix)) {
                return true
            }
        }
    }
    return false
}

func matchResource(patterns []string, resource string) bool {
    for _, p := range patterns {
        if p == "*" || p == resource {
            return true
        }
        if strings.HasSuffix(p, "*") {
            prefix := strings.TrimSuffix(p, "*")
            if strings.HasPrefix(resource, prefix) {
                return true
            }
        }
    }
    return false
}

func matchPrincipal(patterns []string, principal string) bool {
    for _, p := range patterns {
        if p == "*" || p == principal {
            return true
        }
    }
    return false
}

func evaluateConditions(conditions map[string]map[string]string, req IAMRequest) bool {
    if len(conditions) == 0 {
        return true
    }
    
    for condType, condMap := range conditions {
        for key, value := range condMap {
            switch condType {
            case "IpAddress":
                if key == "aws:SourceIp" {
                    _, cidr, err := net.ParseCIDR(value)
                    if err != nil || !cidr.Contains(net.ParseIP(req.SourceIP)) {
                        return false
                    }
                }
            case "Bool":
                if key == "aws:MultiFactorAuthPresent" {
                    if value == "true" && !req.MFAPresent {
                        return false
                    }
                }
            case "StringEquals":
                if key == "aws:RequestedRegion" {
                    // Would check region
                }
            }
        }
    }
    return true
}

// KMS key manager
type KMSKeyManager struct {
    keys    map[string]*KMSKey
    aliases map[string]string // alias -> keyID
    mu      sync.RWMutex
}

type KMSKey struct {
    KeyID         string
    ARN           string
    Description   string
    KeyState      string // Enabled, Disabled, PendingDeletion
    KeyUsage      string // ENCRYPT_DECRYPT, SIGN_VERIFY, GENERATE_VERIFY_MAC
    KeySpec       string // SYMMETRIC_DEFAULT, RSA_2048, ECC_NIST_P256
    Origin        string // AWS_KMS, EXTERNAL, AWS_CLOUDHSM
    MultiRegion   bool
    RotationEnabled bool
    CreatedAt     time.Time
    KeyPolicy     IAMPolicy
    Grants        []KMSGrant
}

type KMSGrant struct {
    GrantID    string
    GranteePrincipal string
    Operations []string
    ExpiresAt  time.Time
}

func NewKMSKeyManager() *KMSKeyManager {
    return &KMSKeyManager{
        keys:    make(map[string]*KMSKey),
        aliases: make(map[string]string),
    }
}

func (m *KMSKeyManager) CreateKey(desc, keySpec, keyUsage string) *KMSKey {
    m.mu.Lock()
    defer m.mu.Unlock()
    
    keyID := fmt.Sprintf("key-%s", generateSecureID())
    key := &KMSKey{
        KeyID:       keyID,
        ARN:         fmt.Sprintf("arn:aws:kms:us-east-1:123456789:key/%s", keyID),
        Description: desc,
        KeyState:    "Enabled",
        KeyUsage:    keyUsage,
        KeySpec:     keySpec,
        Origin:      "AWS_KMS",
        CreatedAt:   time.Now(),
    }
    
    m.keys[keyID] = key
    return key
}

func (m *KMSKeyManager) CreateAlias(alias, keyID string) error {
    m.mu.Lock()
    defer m.mu.Unlock()
    
    if !strings.HasPrefix(alias, "alias/") {
        return fmt.Errorf("alias must start with 'alias/'")
    }
    
    if _, exists := m.keys[keyID]; !exists {
        return fmt.Errorf("key %s not found", keyID)
    }
    
    m.aliases[alias] = keyID
    return nil
}

func (m *KMSKeyManager) ResolveKeyID(keyOrAlias string) (string, error) {
    m.mu.RLock()
    defer m.mu.RUnlock()
    
    if strings.HasPrefix(keyOrAlias, "alias/") {
        keyID, exists := m.aliases[keyOrAlias]
        if !exists {
            return "", fmt.Errorf("alias %s not found", keyOrAlias)
        }
        return keyID, nil
    }
    
    if _, exists := m.keys[keyOrAlias]; exists {
        return keyOrAlias, nil
    }
    
    return "", fmt.Errorf("key %s not found", keyOrAlias)
}

func (m *KMSKeyManager) EnableRotation(keyID string) error {
    m.mu.Lock()
    defer m.mu.Unlock()
    
    key, exists := m.keys[keyID]
    if !exists {
        return fmt.Errorf("key %s not found", keyID)
    }
    
    if key.KeySpec != "SYMMETRIC_DEFAULT" {
        return fmt.Errorf("rotation only supported for symmetric keys")
    }
    
    key.RotationEnabled = true
    return nil
}

func (m *KMSKeyManager) ScheduleDeletion(keyID string, waitingDays int) error {
    m.mu.Lock()
    defer m.mu.Unlock()
    
    key, exists := m.keys[keyID]
    if !exists {
        return fmt.Errorf("key %s not found", keyID)
    }
    
    if waitingDays < 7 || waitingDays > 30 {
        return fmt.Errorf("waiting period must be 7-30 days")
    }
    
    key.KeyState = "PendingDeletion"
    return nil
}

// Secrets Manager
type SecretsManager struct {
    secrets map[string]*Secret
    mu      sync.RWMutex
}

type Secret struct {
    ARN         string
    Name        string
    Description string
    Versions    []SecretVersion
    RotationConfig *RotationConfig
    Tags        map[string]string
    CreatedAt   time.Time
}

type SecretVersion struct {
    VersionID string
    Value     string
    Stage     string // AWSCURRENT, AWSPREVIOUS, AWSPENDING
    CreatedAt time.Time
}

type RotationConfig struct {
    LambdaARN     string
    RotationDays  int
    LastRotated   time.Time
    NextRotation  time.Time
}

func NewSecretsManager() *SecretsManager {
    return &SecretsManager{
        secrets: make(map[string]*Secret),
    }
}

func (sm *SecretsManager) CreateSecret(name, value, description string) (*Secret, error) {
    sm.mu.Lock()
    defer sm.mu.Unlock()
    
    if _, exists := sm.secrets[name]; exists {
        return nil, fmt.Errorf("secret %s already exists", name)
    }
    
    secret := &Secret{
        ARN:         fmt.Sprintf("arn:aws:secretsmanager:us-east-1:123456789:secret:%s-%s", name, generateSecureID()[:6]),
        Name:        name,
        Description: description,
        Tags:        make(map[string]string),
        CreatedAt:   time.Now(),
        Versions: []SecretVersion{
            {
                VersionID: generateSecureID(),
                Value:     value,
                Stage:     "AWSCURRENT",
                CreatedAt: time.Now(),
            },
        },
    }
    
    sm.secrets[name] = secret
    return secret, nil
}

func (sm *SecretsManager) GetSecretValue(name string) (string, error) {
    sm.mu.RLock()
    defer sm.mu.RUnlock()
    
    secret, exists := sm.secrets[name]
    if !exists {
        return "", fmt.Errorf("secret %s not found", name)
    }
    
    for _, v := range secret.Versions {
        if v.Stage == "AWSCURRENT" {
            return v.Value, nil
        }
    }
    
    return "", fmt.Errorf("no current version found")
}

func (sm *SecretsManager) RotateSecret(name, newValue string) error {
    sm.mu.Lock()
    defer sm.mu.Unlock()
    
    secret, exists := sm.secrets[name]
    if !exists {
        return fmt.Errorf("secret %s not found", name)
    }
    
    // Move AWSCURRENT to AWSPREVIOUS
    for i := range secret.Versions {
        if secret.Versions[i].Stage == "AWSPREVIOUS" {
            secret.Versions = append(secret.Versions[:i], secret.Versions[i+1:]...)
            break
        }
    }
    for i := range secret.Versions {
        if secret.Versions[i].Stage == "AWSCURRENT" {
            secret.Versions[i].Stage = "AWSPREVIOUS"
            break
        }
    }
    
    // Add new AWSCURRENT
    secret.Versions = append(secret.Versions, SecretVersion{
        VersionID: generateSecureID(),
        Value:     newValue,
        Stage:     "AWSCURRENT",
        CreatedAt: time.Now(),
    })
    
    if secret.RotationConfig != nil {
        secret.RotationConfig.LastRotated = time.Now()
        secret.RotationConfig.NextRotation = time.Now().AddDate(0, 0, secret.RotationConfig.RotationDays)
    }
    
    return nil
}

func generateSecureID() string {
    return fmt.Sprintf("%016x", time.Now().UnixNano())
}`,
				},
			},
		},
	})
}
