package math

import "github.com/rusik69/lc/internal/problems"

func init() {
	problems.RegisterMathModules([]problems.CourseModule{
		{
			ID:          2011,
			Title:       "Abstract Algebra",
			Description: "Explore groups, rings, and fields - the algebraic structures underlying cryptography and error correction.",
			Order:       11,
			Lessons: []problems.Lesson{
				{
					Title: "Groups and Symmetry",
					Content: `A group (G, ·) is a set G with a binary operation · satisfying four axioms. Groups capture the essence of symmetry.

**Group Axioms:**
1. **Closure**: For all a, b ∈ G: a · b ∈ G
2. **Associativity**: (a · b) · c = a · (b · c)
3. **Identity**: There exists e ∈ G such that a · e = e · a = a
4. **Inverse**: For each a ∈ G, there exists a⁻¹ such that a · a⁻¹ = a⁻¹ · a = e

**Examples of Groups:**
- (ℤ, +): Integers under addition (identity: 0, inverse of n: -n)
- (ℤₙ, +): Integers mod n under addition (used in cryptography)
- (ℤₙ*, ×): Integers mod n coprime to n, under multiplication (RSA)
- Symmetric group Sₙ: All permutations of n elements

**Key Concepts:**
- **Order**: Number of elements in a group (|G|)
- **Subgroup**: Subset that is itself a group under the same operation
- **Lagrange's Theorem**: |subgroup| divides |group|
- **Cyclic Group**: Generated by a single element (g, g², g³, ...)
- **Abelian Group**: Commutative (a · b = b · a)

**Homomorphisms:**
A function φ: G → H preserving structure: φ(a · b) = φ(a) · φ(b)
- **Isomorphism**: Bijective homomorphism (groups are "structurally identical")
- **Kernel**: ker(φ) = {a ∈ G : φ(a) = eH} (always a normal subgroup)

**CS Applications:**
- **Cryptography**: Diffie-Hellman uses cyclic groups; RSA uses ℤₙ*
- **Error-correcting codes**: Group theory for Hamming codes, Reed-Solomon
- **Rubik's cube**: Solved using group theory (the Rubik's group)
- **Symmetry in algorithms**: Exploiting group structure for optimization`,
					CodeExamples: `def is_group(elements, operation, identity):
    """Check if (elements, operation) forms a group."""
    # Closure
    for a in elements:
        for b in elements:
            if operation(a, b) not in elements:
                return False, "Not closed"

    # Associativity (spot check)
    for a in elements:
        for b in elements:
            for c in elements:
                if operation(operation(a, b), c) != operation(a, operation(b, c)):
                    return False, "Not associative"

    # Identity
    for a in elements:
        if operation(a, identity) != a or operation(identity, a) != a:
            return False, "Identity fails"

    # Inverse
    for a in elements:
        found = False
        for b in elements:
            if operation(a, b) == identity and operation(b, a) == identity:
                found = True
                break
        if not found:
            return False, f"No inverse for {a}"

    return True, "Valid group"

# Z_5 under addition mod 5
elements = {0, 1, 2, 3, 4}
add_mod5 = lambda a, b: (a + b) % 5
valid, msg = is_group(elements, add_mod5, 0)
print(f"Z_5 under addition: {msg}")

# Z_5* under multiplication mod 5
elements_star = {1, 2, 3, 4}
mul_mod5 = lambda a, b: (a * b) % 5
valid, msg = is_group(elements_star, mul_mod5, 1)
print(f"Z_5* under multiplication: {msg}")

# Cyclic group generator
def cyclic_group(generator, modulus):
    """Generate cyclic group from a generator."""
    group = []
    current = generator
    while current not in group:
        group.append(current)
        current = (current * generator) % modulus
    return group

print(f"\nCyclic group generated by 2 mod 7: {cyclic_group(2, 7)}")
print(f"Cyclic group generated by 3 mod 7: {cyclic_group(3, 7)}")`,
				},
				{
					Title: "Rings and Fields",
					Content: `Rings and fields extend group theory by adding a second operation, forming the algebraic foundation for number systems and polynomial arithmetic.

**Ring (R, +, ·):**
A ring has two operations satisfying:
1. (R, +) is an abelian group
2. · is associative
3. Distributive laws: a·(b+c) = a·b + a·c and (a+b)·c = a·c + b·c

**Types of Rings:**
- **Commutative Ring**: a·b = b·a (e.g., ℤ, polynomials)
- **Ring with Unity**: Has multiplicative identity (1)
- **Integral Domain**: No zero divisors (ab = 0 implies a = 0 or b = 0)
- **Principal Ideal Domain**: Every ideal is generated by a single element

**Field (F, +, ·):**
A field is a commutative ring where every nonzero element has a multiplicative inverse. In other words, you can divide by any nonzero element.

**Examples:**
- ℚ (rationals), ℝ (reals), ℂ (complex numbers)
- ℤₚ for prime p (finite field, also written GF(p))
- GF(2ⁿ): Extension fields used in AES encryption

**Polynomial Rings:**
R[x] = polynomials with coefficients in R. Polynomial arithmetic over finite fields is central to coding theory.

**CS Applications:**
- **AES Encryption**: Operates in GF(2⁸) = GF(256)
- **CRC Checksums**: Polynomial division over GF(2)
- **Reed-Solomon Codes**: Polynomial interpolation over finite fields
- **Shamir's Secret Sharing**: Polynomial evaluation over finite fields`,
					CodeExamples: `def gf2_poly_multiply(a, b):
    """Multiply two polynomials over GF(2) (XOR arithmetic)."""
    result = 0
    while b:
        if b & 1:
            result ^= a
        a <<= 1
        b >>= 1
    return result

def gf2_poly_mod(a, modulus):
    """Reduce polynomial a modulo modulus over GF(2)."""
    mod_degree = modulus.bit_length() - 1
    while a.bit_length() - 1 >= mod_degree:
        a ^= modulus << (a.bit_length() - 1 - mod_degree)
    return a

# CRC-like computation over GF(2)
data = 0b1101011  # Data polynomial
generator = 0b1011  # Generator polynomial
remainder = gf2_poly_mod(data << (generator.bit_length() - 1), generator)
print(f"CRC remainder: {bin(remainder)}")

# GF(p) arithmetic
def gf_add(a, b, p):
    return (a + b) % p

def gf_mul(a, b, p):
    return (a * b) % p

def gf_inv(a, p):
    """Multiplicative inverse using Fermat's little theorem."""
    return pow(a, p - 2, p)

# Arithmetic in GF(7)
p = 7
print(f"\nGF(7) multiplication table:")
for i in range(1, p):
    row = [gf_mul(i, j, p) for j in range(1, p)]
    print(f"  {i}: {row}")

# Verify inverses exist for all nonzero elements
print(f"\nGF(7) inverses:")
for i in range(1, p):
    inv = gf_inv(i, p)
    print(f"  {i}^(-1) = {inv} (check: {i}*{inv} = {gf_mul(i, inv, p)})")`,
				},
			},
			ProblemIDs: []int{},
		},
		{
			ID:          2012,
			Title:       "Numerical Methods",
			Description: "Learn computational algorithms for solving mathematical problems: root-finding, interpolation, and differential equations.",
			Order:       12,
			Lessons: []problems.Lesson{
				{
					Title: "Root-Finding Algorithms",
					Content: `Root-finding algorithms solve f(x) = 0, one of the most fundamental computational problems.

**Bisection Method:**
- Requires: continuous f with f(a) and f(b) having opposite signs
- Algorithm: repeatedly halve the interval [a, b]
- Convergence: linear, guaranteed, gains one binary digit per iteration
- Rate: error ≤ (b-a)/2ⁿ after n iterations

**Newton's Method (Newton-Raphson):**
- Formula: xₙ₊₁ = xₙ - f(xₙ)/f'(xₙ)
- Convergence: quadratic (digits of accuracy roughly double each step)
- Requires: f'(x) ≠ 0 near root, good initial guess
- Risk: may diverge if initial guess is far from root

**Secant Method:**
- Like Newton's but approximates f'(x) using two previous points
- Formula: xₙ₊₁ = xₙ - f(xₙ) · (xₙ - xₙ₋₁) / (f(xₙ) - f(xₙ₋₁))
- Convergence: superlinear (order ≈ 1.618, the golden ratio)
- No derivative computation required

**Fixed-Point Iteration:**
- Rewrite f(x) = 0 as x = g(x)
- Iterate: xₙ₊₁ = g(xₙ)
- Converges if |g'(x)| < 1 near the fixed point

**Comparison:**
| Method | Convergence | Evaluations/step | Robustness |
|--------|------------|-------------------|------------|
| Bisection | Linear | 1 | Very robust |
| Newton | Quadratic | 2 (f, f') | Fragile |
| Secant | Superlinear | 1 | Moderate |`,
					CodeExamples: `import math

def bisection(f, a, b, tol=1e-10, max_iter=100):
    """Bisection method for root-finding."""
    for i in range(max_iter):
        mid = (a + b) / 2
        if abs(f(mid)) < tol or (b - a) / 2 < tol:
            return mid, i + 1
        if f(a) * f(mid) < 0:
            b = mid
        else:
            a = mid
    return (a + b) / 2, max_iter

def newton(f, df, x0, tol=1e-10, max_iter=100):
    """Newton's method for root-finding."""
    x = x0
    for i in range(max_iter):
        fx = f(x)
        if abs(fx) < tol:
            return x, i + 1
        x = x - fx / df(x)
    return x, max_iter

def secant(f, x0, x1, tol=1e-10, max_iter=100):
    """Secant method for root-finding."""
    for i in range(max_iter):
        f0, f1 = f(x0), f(x1)
        if abs(f1) < tol:
            return x1, i + 1
        x0, x1 = x1, x1 - f1 * (x1 - x0) / (f1 - f0)
    return x1, max_iter

# Find root of x^3 - 2x - 5 = 0 (near x = 2.09)
f = lambda x: x**3 - 2*x - 5
df = lambda x: 3*x**2 - 2

root_b, iters_b = bisection(f, 1, 3)
root_n, iters_n = newton(f, df, 2.0)
root_s, iters_s = secant(f, 1.0, 3.0)

print(f"Root of x^3 - 2x - 5 = 0:")
print(f"  Bisection: {root_b:.10f} ({iters_b} iterations)")
print(f"  Newton:    {root_n:.10f} ({iters_n} iterations)")
print(f"  Secant:    {root_s:.10f} ({iters_s} iterations)")`,
				},
				{
					Title: "Interpolation and Approximation",
					Content: `Interpolation constructs a function that passes through given data points. Approximation finds a "close enough" function.

**Polynomial Interpolation:**

**Lagrange Interpolation:**
Given n+1 points, the unique polynomial of degree ≤ n passing through them:
P(x) = Σᵢ yᵢ · Lᵢ(x), where Lᵢ(x) = Πⱼ≠ᵢ (x - xⱼ)/(xᵢ - xⱼ)

Warning: High-degree polynomials can oscillate wildly (Runge's phenomenon).

**Spline Interpolation:**
Use piecewise low-degree polynomials instead of a single high-degree one.
- **Linear spline**: Connect points with straight lines
- **Cubic spline**: Piecewise cubic with continuous first and second derivatives
- Much more stable than high-degree polynomial interpolation

**Least Squares Approximation:**
When data is noisy, find the best-fit curve minimizing the sum of squared errors:
minimize Σᵢ (yᵢ - f(xᵢ))²

**Linear Regression:** y = mx + b, solved by normal equations: (AᵀA)x = Aᵀb

**CS Applications:**
- Computer graphics: smooth curves and surfaces (Bezier, B-splines)
- Signal reconstruction (Nyquist-Shannon sampling theorem)
- Machine learning: kernel methods, radial basis functions
- Data visualization: smooth trend lines`,
					CodeExamples: `def lagrange_interpolate(points, x):
    """Lagrange polynomial interpolation."""
    n = len(points)
    result = 0.0
    for i in range(n):
        xi, yi = points[i]
        term = yi
        for j in range(n):
            if i != j:
                xj = points[j][0]
                term *= (x - xj) / (xi - xj)
        result += term
    return result

def linear_regression(x_data, y_data):
    """Simple linear regression: y = mx + b."""
    n = len(x_data)
    x_mean = sum(x_data) / n
    y_mean = sum(y_data) / n
    num = sum((x_data[i] - x_mean) * (y_data[i] - y_mean) for i in range(n))
    den = sum((x_data[i] - x_mean) ** 2 for i in range(n))
    m = num / den
    b = y_mean - m * x_mean
    return m, b

# Lagrange interpolation
points = [(0, 1), (1, 3), (2, 9), (3, 19)]
print("Lagrange interpolation through (0,1), (1,3), (2,9), (3,19):")
for x in [0.5, 1.5, 2.5]:
    y = lagrange_interpolate(points, x)
    print(f"  P({x}) = {y:.4f}")

# Linear regression
import random
random.seed(42)
x_data = list(range(20))
y_data = [2 * x + 3 + random.gauss(0, 2) for x in x_data]
m, b = linear_regression(x_data, y_data)
print(f"\nLinear regression on noisy y = 2x + 3:")
print(f"  Fitted: y = {m:.4f}x + {b:.4f}")
print(f"  True:   y = 2.0000x + 3.0000")`,
				},
				{
					Title: "Numerical ODEs",
					Content: `Many real-world systems are described by ordinary differential equations (ODEs) that cannot be solved analytically.

**The Problem:**
Given dy/dt = f(t, y) with y(t₀) = y₀, find y(t) for t > t₀.

**Euler's Method (First Order):**
yₙ₊₁ = yₙ + h · f(tₙ, yₙ)
- Simple but inaccurate: error is O(h)
- Can be unstable for stiff equations

**Improved Euler (Heun's Method):**
1. Predict: ỹ = yₙ + h · f(tₙ, yₙ)
2. Correct: yₙ₊₁ = yₙ + (h/2) · [f(tₙ, yₙ) + f(tₙ₊₁, ỹ)]
- Error is O(h²)

**Runge-Kutta 4th Order (RK4):**
The workhorse of numerical ODE solving:
k₁ = f(tₙ, yₙ)
k₂ = f(tₙ + h/2, yₙ + h·k₁/2)
k₃ = f(tₙ + h/2, yₙ + h·k₂/2)
k₄ = f(tₙ + h, yₙ + h·k₃)
yₙ₊₁ = yₙ + (h/6)(k₁ + 2k₂ + 2k₃ + k₄)
- Error is O(h⁴) - very accurate for smooth problems
- Four function evaluations per step

**Adaptive Step Size:**
Modern solvers (RK45, Dormand-Prince) adjust h automatically to maintain a target error tolerance. This is what scipy.integrate.solve_ivp uses.

**CS Applications:**
- Physics engines in games (projectile motion, collisions)
- Epidemiological models (SIR model for disease spread)
- Financial models (Black-Scholes for option pricing)
- Neural ODEs (continuous-depth neural networks)`,
					CodeExamples: `import math

def euler(f, y0, t0, t_end, h):
    """Euler's method for dy/dt = f(t, y)."""
    t, y = t0, y0
    trajectory = [(t, y)]
    while t < t_end:
        y = y + h * f(t, y)
        t += h
        trajectory.append((t, y))
    return trajectory

def rk4(f, y0, t0, t_end, h):
    """4th-order Runge-Kutta method."""
    t, y = t0, y0
    trajectory = [(t, y)]
    while t < t_end:
        k1 = f(t, y)
        k2 = f(t + h/2, y + h*k1/2)
        k3 = f(t + h/2, y + h*k2/2)
        k4 = f(t + h, y + h*k3)
        y = y + (h/6) * (k1 + 2*k2 + 2*k3 + k4)
        t += h
        trajectory.append((t, y))
    return trajectory

# Solve dy/dt = -2y, y(0) = 1 (exact: y = e^{-2t})
f = lambda t, y: -2 * y
exact = lambda t: math.exp(-2 * t)

euler_traj = euler(f, 1.0, 0, 2, 0.1)
rk4_traj = rk4(f, 1.0, 0, 2, 0.1)

print("Comparing Euler vs RK4 for dy/dt = -2y:")
print(f"{'t':>5} {'Exact':>10} {'Euler':>10} {'RK4':>10} {'Euler err':>10} {'RK4 err':>10}")
for i in range(0, len(euler_traj), 5):
    t_e, y_e = euler_traj[i]
    t_r, y_r = rk4_traj[i]
    ex = exact(t_e)
    print(f"{t_e:5.1f} {ex:10.6f} {y_e:10.6f} {y_r:10.6f} {abs(y_e-ex):10.2e} {abs(y_r-ex):10.2e}")`,
				},
			},
			ProblemIDs: []int{},
		},
		{
			ID:          2013,
			Title:       "Discrete Mathematics for CS",
			Description: "Study logic, proofs, graph theory, and counting techniques essential for algorithm design and verification.",
			Order:       13,
			Lessons: []problems.Lesson{
				{
					Title: "Logic and Proofs",
					Content: `Propositional and predicate logic form the foundation of mathematical reasoning, program verification, and database query languages.

**Propositional Logic:**
- **Propositions**: Statements that are true or false
- **Connectives**: AND (∧), OR (∨), NOT (¬), IMPLIES (→), IFF (↔)
- **Truth Tables**: Enumerate all possible truth values

**Key Equivalences:**
- De Morgan's: ¬(A ∧ B) ≡ ¬A ∨ ¬B and ¬(A ∨ B) ≡ ¬A ∧ ¬B
- Contrapositive: (A → B) ≡ (¬B → ¬A)
- Double Negation: ¬(¬A) ≡ A

**Predicate Logic:**
- **Universal Quantifier (∀)**: "For all" (e.g., ∀x: x² ≥ 0)
- **Existential Quantifier (∃)**: "There exists" (e.g., ∃x: x² = 4)
- **Negation rules**: ¬(∀x: P(x)) ≡ ∃x: ¬P(x)

**Proof Techniques:**
1. **Direct Proof**: Assume P, derive Q
2. **Proof by Contradiction**: Assume ¬Q, derive a contradiction
3. **Proof by Induction**: Base case + inductive step
4. **Proof by Contrapositive**: Prove ¬Q → ¬P instead of P → Q

**CS Applications:**
- Boolean algebra in circuit design
- Program verification (Hoare logic, preconditions/postconditions)
- SQL WHERE clauses are predicate logic
- Type systems use logical inference rules
- SAT solvers for constraint satisfaction`,
					CodeExamples: `def truth_table(expr_name, expr_func, variables):
    """Generate truth table for a Boolean expression."""
    n = len(variables)
    header = " | ".join(variables) + f" | {expr_name}"
    print(header)
    print("-" * len(header))
    for i in range(2**n):
        vals = [(i >> (n-1-j)) & 1 for j in range(n)]
        result = expr_func(*[bool(v) for v in vals])
        row = " | ".join(str(v) for v in vals) + f" | {int(result)}"
        print(row)

# De Morgan's Law: NOT(A AND B) == (NOT A) OR (NOT B)
print("De Morgan's Law verification:")
truth_table("~(A^B)", lambda a, b: not (a and b), ["A", "B"])
print()
truth_table("~A|~B", lambda a, b: (not a) or (not b), ["A", "B"])

# Mathematical induction: prove sum(1..n) = n(n+1)/2
print("\nInduction: sum(1..n) = n(n+1)/2")
print("Base case: n=1: sum=1, formula=1*2/2=1 ✓")
for n in [1, 5, 10, 100, 1000]:
    actual = sum(range(1, n+1))
    formula = n * (n + 1) // 2
    assert actual == formula
    print(f"  n={n:>4}: sum={actual:>6}, formula={formula:>6} ✓")`,
				},
				{
					Title: "Graph Theory Essentials",
					Content: `Graphs model relationships between objects. They are ubiquitous in CS: networks, social graphs, dependency resolution, state machines.

**Terminology:**
- **Graph G = (V, E)**: Vertices V and edges E
- **Degree**: Number of edges incident to a vertex
- **Path**: Sequence of vertices connected by edges
- **Cycle**: Path that starts and ends at the same vertex
- **Connected**: Path exists between every pair of vertices
- **Tree**: Connected acyclic graph (|E| = |V| - 1)

**Graph Types:**
- **Directed (digraph)**: Edges have direction
- **Weighted**: Edges have numerical values
- **Bipartite**: Vertices split into two sets, edges only between sets
- **Complete (Kₙ)**: Every pair of vertices is connected
- **Planar**: Can be drawn without edge crossings

**Key Theorems:**
- **Handshaking Lemma**: Sum of all degrees = 2|E|
- **Euler's Formula (planar)**: V - E + F = 2
- **Four Color Theorem**: Any planar graph can be colored with 4 colors
- **Euler Path**: Exists iff 0 or 2 vertices have odd degree
- **Hamilton Cycle**: NP-complete to determine existence

**CS Applications:**
- **Shortest Path**: Dijkstra, Bellman-Ford, Floyd-Warshall
- **Minimum Spanning Tree**: Kruskal, Prim
- **Topological Sort**: Dependency resolution (build systems, package managers)
- **Network Flow**: Maximum flow, min-cut (network optimization)
- **Graph Coloring**: Register allocation in compilers`,
					CodeExamples: `from collections import defaultdict, deque

class Graph:
    def __init__(self, directed=False):
        self.adj = defaultdict(list)
        self.directed = directed

    def add_edge(self, u, v, weight=1):
        self.adj[u].append((v, weight))
        if not self.directed:
            self.adj[v].append((u, weight))

    def bfs(self, start):
        """BFS traversal returning distances."""
        dist = {start: 0}
        queue = deque([start])
        while queue:
            node = queue.popleft()
            for neighbor, _ in self.adj[node]:
                if neighbor not in dist:
                    dist[neighbor] = dist[node] + 1
                    queue.append(neighbor)
        return dist

    def has_cycle(self):
        """Detect cycle in undirected graph."""
        visited = set()
        def dfs(node, parent):
            visited.add(node)
            for neighbor, _ in self.adj[node]:
                if neighbor not in visited:
                    if dfs(neighbor, node):
                        return True
                elif neighbor != parent:
                    return True
            return False
        for node in self.adj:
            if node not in visited:
                if dfs(node, None):
                    return True
        return False

g = Graph()
for u, v in [(0,1), (1,2), (2,3), (3,0), (2,4)]:
    g.add_edge(u, v)

print(f"BFS from 0: {g.bfs(0)}")
print(f"Has cycle: {g.has_cycle()}")

# Tree check: connected + no cycles + |E| = |V| - 1
tree = Graph()
for u, v in [(0,1), (0,2), (1,3), (1,4)]:
    tree.add_edge(u, v)
print(f"Tree has cycle: {tree.has_cycle()}")`,
				},
			},
			ProblemIDs: []int{},
		},
	})
}
